install:
 - mvn clean
script:
 - mvn -B -fae -Dserver.version=$SERVER_VERSION install

language: java
jdk:
  - oraclejdk8
  - oraclejdk10
env:
  - SERVER_VERSION=12.0.0.Final
  - SERVER_VERSION=13.0.0.Final
  - SERVER_VERSION=14.0.0.Final
cache:
 directories:
  - $HOME/.m2
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - "if [ -d \"$JAVA_HOME/jre\" ]; then SEC_LIB=$JAVA_HOME/jre; else SEC_LIB=$JAVA_HOME; fi; sudo unzip -j -o  travis-libs/jce_policy-8.zip *.jar -d $SEC_LIB/lib/security;"
