install:
 - mvn -B clean
script:
 - travis_wait 60 mvn -B -Ptravis -fae -Dserver.version=$SERVER_VERSION ${ELYTRON:+-Delytron} ${STANDALONE_MICROPROFILE:+-Dts.standalone.microprofile} install

language: java
jdk:
  - openjdk8
env:
  - SERVER_VERSION=23.0.2.Final ELYTRON=true
  - SERVER_VERSION=23.0.2.Final STANDALONE_MICROPROFILE=true
jobs:
addons:
  hosts:
    - localhost.localdomain
cache:
 directories:
  - $HOME/.m2
