install:
 - mvn clean; java -version
script:
 - mvn -B -fae -Dserver.version=$SERVER_VERSION install

language: java
jdk:
  - oraclejdk8
  - oraclejdk9
env:
  - SERVER_VERSION=10.1.0.Final
  - SERVER_VERSION=11.0.0.Final
  - SERVER_VERSION=12.0.0.Final
matrix:
  exclude:
    - jdk: oraclejdk9
      env: SERVER_VERSION=10.1.0.Final
cache:
 directories:
  - $HOME/.m2
addons:
  apt:
    packages:
      - oracle-java8-installer
#      - oracle-java9-installer
